PORTNAME=	installer
PORTVERSION=	22.1
CATEGORIES=	sysutils
PKGNAMEPREFIX=	${GH_ACCOUNT}-

MAINTAINER=	franco@hwasly.org
COMMENT=	HWasly installer scripts
WWW=		https://hwasly.org/

LICENSE=	BSD2CLAUSE

RUN_DEPENDS=	cpdup:sysutils/cpdup
PREFIX=		/usr

NO_ARCH=	yes
NO_BUILD=	yes

USE_GITHUB=	yes
GH_ACCOUNT=	${CATEGORIES:[1]}

.include <bsd.port.mk>
